### ISSUE TITLE
parameter --skip-server-verification not working

### ISSUE THREAD

**Issue by marcosox** [vmware/vsphere-automation-sdk-java#13]
I am trying the ListVMs sample following the instructions provided in the readme.
The server I am connecting to uses a default certificate issued by a non-trusted root CA.
Setting the `--skip-server-verification` seems to do nothing, because the application terminates with an exception regardless of its presence.
The exception is:

    Exception in thread "main" com.vmware.vapi.client.exception.SslException: Host name '[redacted]' does not match the certificate subject provided by the peer (OID.1.2.840.113549.1.9.2="[redacted]", CN=localhost.localdomain, EMAILADDRESS=ssl-certificates@vmware.com, OU=VMware ESX Server Default Certificate, O="VMware, Inc", L=Palo Alto, ST=California, C=US)
        at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.send(HttpClient.java:185)
        at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider.sendRequest(JsonApiProvider.java:126)
        at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider.invoke(JsonApiProvider.java:307)
        at com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:222)
        at com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:203)
        at com.vmware.vapi.internal.bindings.Stub.invokeMethodAsync(Stub.java:167)
        at com.vmware.vapi.internal.bindings.Stub.invokeMethod(Stub.java:135)
        at com.vmware.cis.SessionStub.create(SessionStub.java:44)
        at com.vmware.cis.SessionStub.create(SessionStub.java:37)
        at vmware.samples.common.authentication.VapiAuthenticationHelper.loginByUsernameAndPassword(VapiAuthenticationHelper.java:70)
        at vmware.samples.common.SamplesAbstractBase.login(SamplesAbstractBase.java:306)
        at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:411)
        at vmware.samples.vcenter.vm.list.ListVMs.main(ListVMs.java:128)
    Caused by: javax.net.ssl.SSLPeerUnverifiedException: Host name '[redacted]' does not match the certificate subject provided by the peer (OID.1.2.840.113549.1.9.2="[redacted]", CN=localhost.localdomain, EMAILADDRESS=ssl-certificates@vmware.com, OU=VMware ESX Server Default Certificate, O="VMware, Inc", L=Palo Alto, ST=California, C=US)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:465)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:395)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:353)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.invoke(HttpClient.java:147)
        at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.send(HttpClient.java:166)
        ... 12 more

If I understand the stackTrace correctly, it looks like the Apache commons `HTTPClient` used by the vApi is using its own internal `HostNameVerifier`, which is performing a real verification instead of returning true like the dummy `HostNameVerifier` used in the samples.

I also tried passing `--skip-server-verification true` as the parameter, but with same result.

**Comment by marcosox** [comment]
I forgot to mention that I'm connecting using the IP address of the server, and I'm having the same exact problem as the guy in [this post](https://communities.vmware.com/thread/564492).

**Comment by vinpai** [comment]
For the time being, use the fully qualified hostname. I will fix this shortly. Also, note that skipping SSL verification is unsafe and not to be used in production environments. This is added only for testing/development purpose.

**Comment by marcosox** [comment]
No problem since this is being used in dev.
I can't use the fully qualified hostname because it is non resolvable and I can't change it at the moment. Meanwhile I switched to YaviJava, but I'll give this another try when it's fixed.
Thanks for your support
