### ISSUE TITLE
"java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager" issue while running ListVMs sample

### ISSUE THREAD

**Issue by necromorph98** [vmware/vsphere-automation-sdk-java#175]
## Description
I recently installed vsphere sdk 8.0.0 because iwant to develop plugins for vcenter. I followed the installation guide but when i run the first sample ListVMs, i get the following error,

```
necromorph@necro-2004:~/Downloads/opt/vsphere-automation-sdk-java$ java -ea -cp target/vsphere-samples-8.0.0.1.jar vmware.samples.vcenter.vm.list.ListVMs --server 192.168.29.144 --username administrator@vsphere.local --password 123456Abcd --skip-server-verification

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
 Connect Failed 
java.lang.NullPointerException: Cannot invoke "com.vmware.vim25.ServiceContent.getSessionManager()" because "this.serviceContent" is null
        at vmware.samples.common.authentication.VimAuthenticationHelper.logout(VimAuthenticationHelper.java:105)
        at vmware.samples.common.SamplesAbstractBase.logout(SamplesAbstractBase.java:411)
        at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:448)
        at vmware.samples.vcenter.vm.list.ListVMs.main(ListVMs.java:128)
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
        at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
        at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:349)
        at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:335)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:293)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:202)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:183)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:179)
        at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
        at javax.xml.ws.Service.<init>(Service.java:82)
        at com.vmware.vim25.VimService.<init>(Unknown Source)
        at vmware.samples.common.authentication.VimAuthenticationHelper.loginByUsernameAndPassword(VimAuthenticationHelper.java:74)
        at vmware.samples.common.SamplesAbstractBase.login(SamplesAbstractBase.java:311)
        at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:433)
        at vmware.samples.vcenter.vm.list.ListVMs.main(ListVMs.java:128)
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more
```

I fixed this issue by adding a dependency for slf4j-simple to pom.xml

```
<dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <version>${slf4j.version}</version>
</dependency>
```

But now i am running into the following error

```
[main] INFO com.vmware.vapi.internal.tracing.otel.OtelFeature - OpenTelemetry is not on the classpath
[main] WARN com.vmware.vapi.internal.protocol.client.rpc.http.TrustAllX509TrustManager - Skipped the validation of a certificate chain due to configuration policy. Your connection is not secure!
[main] WARN com.vmware.vapi.internal.protocol.client.rpc.http.AllowAllHostnameVerifier - Cannot validate the identity of 192.168.29.144 due to the hostname-verification being disabled. You are susceptible to man-in-the-middle attacks!
 Connect Failed 
java.lang.NullPointerException: Cannot invoke "com.vmware.vim25.ServiceContent.getSessionManager()" because "this.serviceContent" is null
        at vmware.samples.common.authentication.VimAuthenticationHelper.logout(VimAuthenticationHelper.java:105)
        at vmware.samples.common.SamplesAbstractBase.logout(SamplesAbstractBase.java:411)
        at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:448)
        at vmware.samples.vcenter.vm.list.ListVMs.main(ListVMs.java:128)
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
        at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296)
        at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:349)
        at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:335)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:293)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:202)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:183)
        at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:179)
        at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89)
        at javax.xml.ws.Service.<init>(Service.java:82)
        at com.vmware.vim25.VimService.<init>(Unknown Source)
        at vmware.samples.common.authentication.VimAuthenticationHelper.loginByUsernameAndPassword(VimAuthenticationHelper.java:74)
        at vmware.samples.common.SamplesAbstractBase.login(SamplesAbstractBase.java:311)
        at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:433)
        at vmware.samples.vcenter.vm.list.ListVMs.main(ListVMs.java:128)
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 14 more
```

- SDK version: 8.0.0

- Java version: 19.0.2

- vSphere version: 8.0

**Comment by necromorph98** [comment]
I fixed it by using jdk 8 instead of jdk 19
