### ISSUE TITLE
Incompatibility with Java 11

### ISSUE THREAD

**Issue by gdelhumeau** [vmware/vsphere-automation-sdk-java#199]
- [x] I am using the [latest SDK version](https://github.com/vmware/vsphere-automation-sdk-java/releases)
- [x] This API is compatible with my vCenter version (You can get this info from the API documentation )
- [x] I have searched [existing issues](https://github.com/vmware/vsphere-automation-sdk-java/issues?utf8=%E2%9C%93&q=is%3Aissue)

## Environment
- SDK version: 
`vsphere-automation-sdk-java-8.0.1.0.1`

- Java version:
`openjdk 11.0.20.1 2023-08-24`

- vSphere version:
Not relevant

## Steps or code snippet to reproduce

I am trying to create a session from my program:
`java -cp "path/to/my.jar:~/Downloads/vsphere-automation-sdk-java-8.0.1.0.1/lib/*" path.to.my.MainClass`

## Actual behavior
I got the following stack trace:

```
Caused by: javax.xml.ws.WebServiceException: Provider com.sun.xml.internal.ws.spi.ProviderImpl not found
	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:61)
	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:58)
	at javax.xml.ws.spi.ServiceLoaderUtil.newInstance(ServiceLoaderUtil.java:103)
	at javax.xml.ws.spi.FactoryFinder.find(FactoryFinder.java:112)
	at javax.xml.ws.spi.Provider.provider(Provider.java:96)
	at javax.xml.ws.Service.<init>(Service.java:112)
	at com.vmware.vim25.VimService.<init>(VimService.java:38)
	at com.xwiki.cloud.infra.vsphere.internal.DefaultVSphereSessionFactory.getVSphereClient(DefaultVSphereSessionFactory.java:58)
	at com.xwiki.cloud.infra.instance.virtualhardware.vsphere.VSphereBridge.initialize(VSphereBridge.java:127)
	... 9 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.ws.spi.ProviderImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	at javax.xml.ws.spi.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:90)
	at javax.xml.ws.spi.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:123)
	at javax.xml.ws.spi.ServiceLoaderUtil.newInstance(ServiceLoaderUtil.java:101)
	... 15 more
```

## Expected behavior
I get a session to my vSphere instance.

**Comment by aagrawal3** [comment]
Hi @gdelhumeau 

There are some packages which were removed in JDK11. So, it needs to be explicitly added to build files as we did in case of our SDK [here](https://github.com/vmware/vsphere-automation-sdk-java/blob/master/pom.xml#L38)

It looks like you are using a build script of your own and directly using the libraries from `vsphere-automation-sdk-java-8.0.1.0.1/lib/*`. 
Please make sure that the missing packages are present in your build script.

Alternatively, you could compile our SDK and use the compiled jar with all dependecies from target dir.

**Comment by aagrawal3** [comment]
Please reopen if the issue persists.
