### ISSUE TITLE
cannot convert VMTypes.Info into VMTypes.CreateSpec

### ISSUE THREAD

**Issue by rdxnaor** [vmware/vsphere-automation-sdk-java#25]
Tried to use "_converTo" but got :
Exception in thread "main" com.vmware.vapi.bindings.convert.ConverterException: Could not convert field 'name' of structure 'com.vmware.vcenter.VM.create_spec'
	at com.vmware.vapi.internal.bindings.convert.impl.JavaClassStructConverter.fromValue(JavaClassStructConverter.java:89)
	at com.vmware.vapi.internal.bindings.convert.impl.JavaClassStructConverter.fromValue(JavaClassStructConverter.java:33)
	at com.vmware.vapi.internal.bindings.TypeConverterImpl$ValueToJavaVisitor.visit(TypeConverterImpl.java:279)
	at com.vmware.vapi.bindings.type.StructType.accept(StructType.java:372)
	at com.vmware.vapi.internal.bindings.TypeConverterImpl.convertToJava(TypeConverterImpl.java:688)
	at com.vmware.vapi.internal.bindings.BindingsUtil.convertTo(BindingsUtil.java:497)
	at com.vmware.vapi.internal.bindings.BindingsUtil.convertTo(BindingsUtil.java:480)
	at com.vmware.vcenter.VMTypes$Info._convertTo(VMTypes.java:1874)

**Comment by vinpai** [comment]
What were you trying to to do when you got the exception ? Is there a code sample you can attach that we can look at ?  Also, please note that as per apidoc,  if conversion is not possible it will throw an exception.

<T extends Structure> T _convertTo(Class<T> clazz)
Converts this structure into an instance of the provided class structure if possible. A conversion will be possible if the requested structure's fields are all present in this structure.
Parameters:
clazz - type of the result structure. cannot be null.
Returns:
an instance of the requested type if conversion is possible. CoreException is thrown otherwise.

In most cases you wouldn't need to use this method. So, if you can paste code your code snippet it will help.

**Comment by rdxnaor** [comment]
Don't have the code since I found out that this sdk lakes most of the operations I need. 
But it basically going from VMTypes.Info to VMTypes.CreateSpec. If thought that if I managed to do that manually - you guys provided it automatically. Unfortunately its not working.

I tried to do it because I wanted to create a similar VM without a template. If you think that its a common use case you should fix that.

**Comment by strefethen** [comment]
@rdxnaor would you mind listing the operations that you need that you're missing? I'd like to be sure we have those things in our backlogged and prioritized correctly for our API team.

Thanks,
-Steve
vSphere SDK Dev Manager

**Comment by rdxnaor** [comment]
Sure
vcenter
1. add datastore
2. rescan datastore for new VM's
3. all assignments to datastore (to host, cluster, vm)

VM operaions
1. create snapshot
2. create clone
3. VMotion

If I encounter more operations, I'll write them down. 

Thanks.

**Comment by rdxnaor** [comment]
Just continued to write my code and there are more operations. didn't check if there are already exists.

1. discover iscsi target via ip
2. connect to iscsi target
