### ISSUE TITLE
After Start next operations are not working, timeouts after an hour but no operations are performed

### ISSUE THREAD

**Issue by LakshmanPatil** [vmware/vsphere-automation-sdk-java#67]
I am getting this issue while running the Power Cycle, When VM gets turned on, after that next operations are not working. 

Getting this exception
Exception in thread "main" com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: java.net.SocketException: Network is unreachable: connect
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:208)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
	at com.sun.xml.internal.ws.client.sei.SEIStub.doProcess(SEIStub.java:178)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:93)
	at com.sun.xml.internal.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:77)
	at com.sun.xml.internal.ws.client.sei.SEIStub.invoke(SEIStub.java:147)
	at com.sun.proxy.$Proxy37.retrieveProperties(Unknown Source)
	at vmware.samples.common.vim.helpers.VimUtil.getCluster(VimUtil.java:121)
	at vmware.samples.VMOperations.getMORforHost(VMOperations.java:128)
	at vmware.samples.VMOperations.main(VMOperations.java:45)
Caused by: java.net.SocketException: Network is unreachable: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1199)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:259)
	at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
	... 16 more

----------------------------------------------------------------------------------------------------------

After VM on this error is displayed

Exception in thread "main" com.vmware.vapi.client.exception.ConnectionException: https://10.98.34.54:443/api invocation failed with "java.net.SocketException: Connection reset"
	at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.send(HttpClient.java:196)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider.sendRequest(JsonApiProvider.java:125)
	at com.vmware.vapi.internal.protocol.client.msg.json.JsonApiProvider.invoke(JsonApiProvider.java:306)
	at com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:227)
	at com.vmware.vapi.internal.bindings.Stub.invoke(Stub.java:208)
	at com.vmware.vapi.internal.bindings.Stub.invokeMethodAsync(Stub.java:172)
	at com.vmware.vapi.internal.bindings.Stub.invokeMethod(Stub.java:140)
	at com.vmware.vcenter.vm.PowerStub.start(PowerStub.java:82)
	at com.vmware.vcenter.vm.PowerStub.start(PowerStub.java:75)
	at vmware.samples.VMOperations.run(VMOperations.java:120)
	at vmware.samples.common.SamplesAbstractBase.execute(SamplesAbstractBase.java:366)
	at vmware.samples.VMOperations.main(VMOperations.java:56)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.invoke(HttpClient.java:156)
	at com.vmware.vapi.internal.protocol.client.rpc.http.HttpClient.send(HttpClient.java:176)
	... 11 more

Following the version information
Vsphere: 6.7.0  
JDK: 1.8

Please do the needful

**Comment by jobingeo** [comment]
Are you trying to perform an operation in the same VM which went some power cycle? The sequence of operation will provide clarity here.

**Comment by LakshmanPatil** [comment]
I am reverting to a particular snapshot and creating a new snapshot. After that turning on the VM. 
In the Run(), powerService.start() is called then it is not returning. 
After debugging, thread is stuck at below mentioned point.
this.invokeMethod(new MethodIdentifier(this.ifaceId, "start"), strBuilder, PowerDefinitions.__startInput, PowerDefinitions.__startOutput, Arrays.asList(new 13(this), new 14(this), new 15(this), new 16(this), new 17(this), new 18(this), new 19(this), new 20(this), new 21(this), new 22(this), new 23(this)), invocationConfig);

**Comment by kunal-pmj** [comment]
Hi @LakshmanPatil 

Can you share the source code of VMOperations .java at [gist](https://gist.github.com/)?

Thanks
Kunal

**Comment by LakshmanPatil** [comment]
Hi @kunal-pmj 
Please find the source code.
https://gist.github.com/LakshmanPatil/2ce15a991b2476b60b89df6e78bc5893
Thanks 
Lakshman

**Comment by LakshmanPatil** [comment]
@kunal-pmj 
Any update on the above issue?? Also I have tried just running the PowerCycle even that also stuck at Start and stop.Can you please help?

**Comment by kunal-pmj** [comment]
Hi @LakshmanPatil 

We are looking into the issue.

Thanks
Kunal

**Comment by jobingeo** [comment]
The code looks good. No issues with power operations code snippet.  Here is the o/p of execution
---------------------------------
With VM in powered OFF
--------
Using VM: Sample_Basic_VM_for_Simple_Testbed (vmId=vm-65 ) for Power Operations 
sample.
Creating new snapshot is in progress
Taking snapshot : [Test creation snapshot]
Snapshot - [Test creation snapshot] Creation Successful
Revert to a snapshot is in progress
# Example: Get current vm power state
# Example: Power on the vm
# Cleanup: Power off the vm
vm.power->stop()
VM is powered off
-------------------------
With VM in powered ON
--------------------------
Using VM: Sample_Basic_VM_for_Simple_Testbed (vmId=vm-65 ) for Power Operations 
sample.
Creating new snapshot is in progress
Taking snapshot : [Test creation snapshot]
Snapshot - [Test creation snapshot] Creation Successful
Revert to a snapshot is in progress
# Example: Get current vm power state
# Example: VM is powered on, power it off
# Example: Power on the vm
# Cleanup: Power off the vm
vm.power->stop()
VM is powered off
--------------------------------------------
You can also refer to example code, in https://github.com/vmware/vsphere-automation-sdk-java/blob/master/src/main/java/vmware/samples/vcenter/vm/power/PowerLifeCycle.java

**Comment by LakshmanPatil** [comment]
Hi @jobingeo :
The issue is not resolved still I am facing the same issue. Below is the o/p execution.
Clean up is not running on. Start operation is running continuously.  Can you please look into it.

```
Using VM: WEPOS 2 (vmId=vm-815 ) for Power Operations sample.
Creating new snapshot is in progress
Taking snapshot : [Test creation snapshot]
Snapshot - [Test creation snapshot] Creation Successful
Revert to a snapshot is in progress
 Reverting Snapshot - [ Complete ] Successful 
# Example: Get current vm power state
# Example: Power on the vm
```

**Comment by jobingeo** [comment]
Java bindings are working fine. Verified this with the sample code and user provided code. 
This is an environment issue.
